### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by Mologasta** [Mologasta/game-portal#1]
Any suggestions

**Comment by oleh-shalyhin** [comment]
I've just reviewed your committed code and have some suggestions how to improve the code and project structure:
1) Move all the folders and files to the root, don't keep them in Site folder.
2) Delete unused images and libraries. You use libraries from CDN, so delete all the bootstrap files from css, js and fonts folder. And npm.js too.
3) Move css, img and fonts folders into assets folder (it's common convention).

**Comment by Mologasta** [comment]
Done

**Comment by oleh-shalyhin** [comment]
Verified
